services:
  - type: static_site
    name: sclark003-frontend
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: dist

  - type: web
    name: sclark003-backend
    env: python
    plan: starter
    root: backend
    buildCommand: pip install --extra-index-url https://download.pytorch.org/whl/cpu -r requirements.txt
    envVars:
      - key: WEB_CONCURRENCY
        value: "1"
      - key: PIP_EXTRA_INDEX_URL
        value: https://download.pytorch.org/whl/cpu
      - key: PORT
        value: "8000"
    startCommand: gunicorn app:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:${PORT:-8000} --workers 1
